from __future__ import annotations

MG_MOLAR_MASS_G_PER_MOL = 24.305
CA_MOLAR_MASS_G_PER_MOL = 40.078
MG_DENSITY_G_PER_CM3 = 1.738
CA_DENSITY_G_PER_CM3 = 1.55

# Biology anchors
SERUM_CA_NORMAL_MG_DL_MIN = 8.5
SERUM_CA_NORMAL_MG_DL_MAX = 10.5
SERUM_MG_NORMAL_MG_DL_MIN = 1.7
SERUM_MG_NORMAL_MG_DL_MAX = 2.2
